import type { InventoryItem } from "@/lib/types"

export const mockInventory: InventoryItem[] = [
  {
    id: "inv1",
    name: "Chicken Breast",
    category: "Meat",
    unit: "kg",
    quantity: 25,
    minQuantity: 10,
    maxQuantity: 50,
    unitPrice: 450,
    supplier: "Fresh Meats Ltd",
    lastRestocked: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "inv2",
    name: "Beef Steak",
    category: "Meat",
    unit: "kg",
    quantity: 8,
    minQuantity: 10,
    maxQuantity: 30,
    unitPrice: 850,
    supplier: "Fresh Meats Ltd",
    lastRestocked: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "inv3",
    name: "Fresh Fish",
    category: "Seafood",
    unit: "kg",
    quantity: 15,
    minQuantity: 8,
    maxQuantity: 25,
    unitPrice: 650,
    supplier: "Ocean Fresh",
    lastRestocked: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "inv4",
    name: "Eggs",
    category: "Dairy",
    unit: "tray",
    quantity: 12,
    minQuantity: 5,
    maxQuantity: 20,
    unitPrice: 350,
    supplier: "Farm Fresh",
    lastRestocked: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "inv5",
    name: "Milk",
    category: "Dairy",
    unit: "liters",
    quantity: 30,
    minQuantity: 15,
    maxQuantity: 50,
    unitPrice: 120,
    supplier: "Farm Fresh",
    lastRestocked: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "inv6",
    name: "Tomatoes",
    category: "Vegetables",
    unit: "kg",
    quantity: 18,
    minQuantity: 10,
    maxQuantity: 30,
    unitPrice: 80,
    supplier: "Green Valley",
    lastRestocked: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "inv7",
    name: "Potatoes",
    category: "Vegetables",
    unit: "kg",
    quantity: 45,
    minQuantity: 20,
    maxQuantity: 60,
    unitPrice: 60,
    supplier: "Green Valley",
    lastRestocked: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "inv8",
    name: "Cooking Oil",
    category: "Pantry",
    unit: "liters",
    quantity: 22,
    minQuantity: 15,
    maxQuantity: 40,
    unitPrice: 280,
    supplier: "General Supplies",
    lastRestocked: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "inv9",
    name: "Rice",
    category: "Pantry",
    unit: "kg",
    quantity: 55,
    minQuantity: 30,
    maxQuantity: 80,
    unitPrice: 120,
    supplier: "General Supplies",
    lastRestocked: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "inv10",
    name: "Coffee Beans",
    category: "Beverages",
    unit: "kg",
    quantity: 6,
    minQuantity: 8,
    maxQuantity: 20,
    unitPrice: 1200,
    supplier: "Coffee Masters",
    lastRestocked: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
]
