import type { MenuItem } from "@/lib/types"

export const mockMenuItems: MenuItem[] = [
  // Breakfast
  {
    id: "m1",
    name: "Full English Breakfast",
    description: "Eggs, bacon, sausage, beans, toast, and mushrooms",
    category: "Breakfast",
    price: 850,
    isAvailable: true,
    preparationTime: 15,
    ingredients: ["eggs", "bacon", "sausage", "beans", "bread", "mushrooms"],
  },
  {
    id: "m2",
    name: "Pancakes with Syrup",
    description: "Fluffy pancakes served with maple syrup and butter",
    category: "Breakfast",
    price: 450,
    isAvailable: true,
    preparationTime: 10,
  },
  {
    id: "m3",
    name: "Omelette",
    description: "Three-egg omelette with cheese and vegetables",
    category: "Breakfast",
    price: 550,
    isAvailable: true,
    preparationTime: 12,
  },
  // Main Course
  {
    id: "m4",
    name: "Grilled Chicken",
    description: "Tender grilled chicken breast with vegetables and rice",
    category: "Main Course",
    price: 1200,
    isAvailable: true,
    preparationTime: 25,
  },
  {
    id: "m5",
    name: "Beef Steak",
    description: "Premium beef steak with mashed potatoes and gravy",
    category: "Main Course",
    price: 1800,
    isAvailable: true,
    preparationTime: 30,
  },
  {
    id: "m6",
    name: "Fish & Chips",
    description: "Crispy battered fish with french fries and tartar sauce",
    category: "Main Course",
    price: 950,
    isAvailable: true,
    preparationTime: 20,
  },
  {
    id: "m7",
    name: "Vegetable Pasta",
    description: "Pasta with mixed vegetables in creamy sauce",
    category: "Main Course",
    price: 750,
    isAvailable: true,
    preparationTime: 18,
  },
  // Beverages
  {
    id: "m8",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    category: "Beverages",
    price: 250,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: "m9",
    name: "Coffee",
    description: "Hot brewed coffee",
    category: "Beverages",
    price: 150,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: "m10",
    name: "Soft Drink",
    description: "Assorted soft drinks",
    category: "Beverages",
    price: 120,
    isAvailable: true,
    preparationTime: 2,
  },
  // Desserts
  {
    id: "m11",
    name: "Chocolate Cake",
    description: "Rich chocolate cake with vanilla ice cream",
    category: "Desserts",
    price: 450,
    isAvailable: true,
    preparationTime: 8,
  },
  {
    id: "m12",
    name: "Ice Cream Sundae",
    description: "Three scoops of ice cream with toppings",
    category: "Desserts",
    price: 350,
    isAvailable: true,
    preparationTime: 5,
  },
]

export const menuCategories = ["All", "Breakfast", "Main Course", "Beverages", "Desserts"]
