export const mockReports = {
  summary: {
    totalRevenue: 2450000,
    revenueGrowth: 12.5,
    totalOrders: 856,
    averageOrderValue: 2862,
    customersServed: 1240,
    repeatCustomers: 35,
    lowStockItems: 8,
  },
  sales: {
    dailySales: [
      { date: "Jan 1", revenue: 78000, orders: 28 },
      { date: "Jan 2", revenue: 82000, orders: 31 },
      { date: "Jan 3", revenue: 75000, orders: 26 },
      { date: "Jan 4", revenue: 91000, orders: 35 },
      { date: "Jan 5", revenue: 88000, orders: 32 },
      { date: "Jan 6", revenue: 95000, orders: 38 },
      { date: "Jan 7", revenue: 102000, orders: 42 },
    ],
    byCategory: [
      { category: "Main Course", revenue: 980000, orders: 420 },
      { category: "Beverages", revenue: 560000, orders: 680 },
      { category: "Appetizers", revenue: 420000, orders: 380 },
      { category: "Desserts", revenue: 280000, orders: 320 },
      { category: "Breakfast", revenue: 210000, orders: 180 },
    ],
    topItems: [
      { name: "Grilled Chicken", quantity: 145, revenue: 435000, percentage: 17.8 },
      { name: "Beef Stew", quantity: 128, revenue: 384000, percentage: 15.7 },
      { name: "Fresh Juice", quantity: 256, revenue: 256000, percentage: 10.4 },
      { name: "Ugali & Fish", quantity: 98, revenue: 294000, percentage: 12.0 },
      { name: "Pilau", quantity: 112, revenue: 280000, percentage: 11.4 },
    ],
    orderTypes: [
      { type: "dine-in", count: 512, percentage: 60 },
      { type: "takeaway", count: 256, percentage: 30 },
      { type: "room-service", count: 88, percentage: 10 },
    ],
  },
  staff: {
    performance: [
      {
        id: "1",
        name: "John Kamau",
        role: "waiter",
        ordersServed: 156,
        rating: 4.8,
        avgServiceTime: 12,
        revenue: 468000,
        performance: "excellent",
      },
      {
        id: "2",
        name: "Mary Wanjiku",
        role: "waiter",
        ordersServed: 142,
        rating: 4.6,
        avgServiceTime: 14,
        revenue: 426000,
        performance: "excellent",
      },
      {
        id: "3",
        name: "Peter Omondi",
        role: "waiter",
        ordersServed: 128,
        rating: 4.4,
        avgServiceTime: 15,
        revenue: 384000,
        performance: "good",
      },
    ],
    maxRevenue: 468000,
    topPerformers: [
      { name: "John Kamau", metric: "Highest Revenue" },
      { name: "Mary Wanjiku", metric: "Best Rating" },
      { name: "Peter Omondi", metric: "Most Orders" },
    ],
    shiftCoverage: [
      { shift: "Morning (6AM - 2PM)", staff: 8, coverage: 100 },
      { shift: "Afternoon (2PM - 10PM)", staff: 10, coverage: 100 },
      { shift: "Night (10PM - 6AM)", staff: 4, coverage: 80 },
    ],
  },
  inventory: {
    summary: {
      totalItems: 124,
      categories: 4,
      lowStock: 8,
      wasteValue: 45000,
      wastePercentage: 1.8,
    },
    lowStockItems: [
      { id: "1", name: "Rice", category: "ingredients", quantity: 15, unit: "kg", reorderLevel: 50 },
      { id: "2", name: "Cooking Oil", category: "ingredients", quantity: 8, unit: "l", reorderLevel: 20 },
      { id: "3", name: "Tomatoes", category: "ingredients", quantity: 5, unit: "kg", reorderLevel: 15 },
      { id: "4", name: "Onions", category: "ingredients", quantity: 6, unit: "kg", reorderLevel: 20 },
    ],
    mostUsed: [
      { name: "Rice", used: 185, unit: "kg", frequency: "Daily", percentage: 100 },
      { name: "Cooking Oil", used: 42, unit: "l", frequency: "Daily", percentage: 85 },
      { name: "Tomatoes", used: 95, unit: "kg", frequency: "Daily", percentage: 75 },
      { name: "Onions", used: 78, unit: "kg", frequency: "Daily", percentage: 65 },
    ],
    wasteLog: [
      { item: "Lettuce", quantity: 3, unit: "kg", reason: "Spoiled", value: 1200, date: "2025-01-15" },
      { item: "Milk", quantity: 5, unit: "l", reason: "Expired", value: 800, date: "2025-01-14" },
      { item: "Bread", quantity: 12, unit: "pcs", reason: "Stale", value: 600, date: "2025-01-13" },
    ],
  },
}
