# Generated by Django 5.0.2 on 2025-09-30 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('other', 'Other')], default='national_id', max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('guest_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('group', 'Group'), ('corporate', 'Corporate'), ('vip', 'VIP')], default='individual', max_length=20)),
                ('company', models.CharField(blank=True, help_text='For corporate guests', max_length=200)),
                ('room_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Check-in'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('expected_checkin', models.DateTimeField()),
                ('actual_checkin', models.DateTimeField(blank=True, null=True)),
                ('expected_checkout', models.DateTimeField()),
                ('actual_checkout', models.DateTimeField(blank=True, null=True)),
                ('dietary_preferences', models.TextField(blank=True, help_text='Vegetarian, allergies, etc.')),
                ('special_requests', models.TextField(blank=True)),
                ('preferred_language', models.CharField(default='english', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('corporate', 'Corporate Account')], default='cash', max_length=20)),
                ('housekeeping_preferences', models.TextField(blank=True)),
                ('minibar_access', models.BooleanField(default=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('loyalty_number', models.CharField(blank=True, max_length=50)),
                ('previous_stays', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['receptionist', 'manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': 'guests',
                'ordering': ['-created_at'],
                'unique_together': {('room_number', 'expected_checkin')},
            },
        ),
        migrations.CreateModel(
            name='GuestFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('room', 'Room Quality'), ('service', 'Service Quality'), ('food', 'Food & Dining'), ('cleanliness', 'Cleanliness'), ('staff', 'Staff Behavior'), ('amenities', 'Amenities'), ('value', 'Value for Money'), ('overall', 'Overall Experience')], max_length=20)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('management_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='guests.guest')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Feedback',
                'verbose_name_plural': 'Guest Feedback',
                'db_table': 'guest_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('total_guests', models.PositiveIntegerField()),
                ('group_type', models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('corporate', 'Corporate'), ('wedding', 'Wedding Party'), ('tour', 'Tour Group'), ('conference', 'Conference'), ('other', 'Other')], max_length=20)),
                ('group_rate_applied', models.BooleanField(default=False)),
                ('group_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('special_arrangements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Guest Group',
                'verbose_name_plural': 'Guest Groups',
                'db_table': 'guest_groups',
            },
        ),
        migrations.CreateModel(
            name='GuestPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('room', 'Room Preferences'), ('food', 'Food & Dining'), ('service', 'Service Preferences'), ('communication', 'Communication'), ('amenities', 'Amenities')], max_length=20)),
                ('preference_key', models.CharField(max_length=100)),
                ('preference_value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Guest Preference',
                'verbose_name_plural': 'Guest Preferences',
                'db_table': 'guest_preferences',
                'unique_together': {('guest', 'category', 'preference_key')},
            },
        ),
    ]
