# Generated by Django 5.0.2 on 2025-09-30 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dine_in_orders', models.PositiveIntegerField(default=0)),
                ('room_service_orders', models.PositiveIntegerField(default=0)),
                ('takeaway_orders', models.PositiveIntegerField(default=0)),
                ('food_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beverage_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxes_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('new_checkins', models.PositiveIntegerField(default=0)),
                ('checkouts', models.PositiveIntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_requests', models.PositiveIntegerField(default=0)),
                ('completed_requests', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('active_staff', models.PositiveIntegerField(default=0)),
                ('low_stock_items', models.PositiveIntegerField(default=0)),
                ('out_of_stock_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Stats',
                'verbose_name_plural': 'Dashboard Stats',
                'db_table': 'dashboard_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HourlySales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField()),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hourly Sales',
                'verbose_name_plural': 'Hourly Sales',
                'db_table': 'hourly_sales',
                'ordering': ['-date', '-hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beverage_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('room_service_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operational_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Report',
                'verbose_name_plural': 'Revenue Reports',
                'db_table': 'revenue_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('morning_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('afternoon_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evening_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Data',
                'verbose_name_plural': 'Sales Data',
                'db_table': 'sales_data',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='CategorySales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='menu.category')),
            ],
            options={
                'verbose_name': 'Category Sales',
                'verbose_name_plural': 'Category Sales',
                'db_table': 'category_sales',
                'ordering': ['-date', '-total_sales'],
                'unique_together': {('date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PopularItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('times_ordered', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('popularity_rank', models.PositiveIntegerField(default=0)),
                ('revenue_rank', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_data', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Popular Item',
                'verbose_name_plural': 'Popular Items',
                'db_table': 'popular_items',
                'ordering': ['-date', 'popularity_rank'],
                'unique_together': {('date', 'menu_item')},
            },
        ),
    ]
