# Generated by Django 5.0.2 on 2025-09-30 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('pesapal', 'PesaPal'), ('mpesa', 'M-Pesa STK Push'), ('manual', 'Manual Processing')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
                ('supports_cards', models.BooleanField(default=False)),
                ('supports_mobile_money', models.BooleanField(default=False)),
                ('supports_bank_transfers', models.BooleanField(default=False)),
                ('transaction_fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet'), ('voucher', 'Voucher/Gift Card'), ('room_charge', 'Room Charge')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partial_refund', 'Partially Refunded')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=50)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=10)),
                ('mobile_money_number', models.CharField(blank=True, max_length=17)),
                ('mobile_money_provider', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tkash', 'T-Kash'), ('other', 'Other')], max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['cashier', 'admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'payment_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('reconciliation', 'Reconciliation')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_payments', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gateway_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_processing_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Report',
                'verbose_name_plural': 'Payment Reports',
                'db_table': 'payment_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Split',
                'verbose_name_plural': 'Payment Splits',
                'db_table': 'payment_splits',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], max_length=20)),
                ('gateway_response', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'Payment Attempt',
                'verbose_name_plural': 'Payment Attempts',
                'db_table': 'payment_attempts',
                'ordering': ['-started_at'],
                'unique_together': {('payment', 'attempt_number')},
            },
        ),
    ]
