# Generated by Django 5.0.2 on 2025-09-30 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(default=800, help_text='Layout width in pixels')),
                ('height', models.PositiveIntegerField(default=600, help_text='Layout height in pixels')),
                ('floor_plan_image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table Layout',
                'verbose_name_plural': 'Table Layouts',
                'db_table': 'table_layouts',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('section', models.CharField(choices=[('main_dining', 'Main Dining'), ('terrace', 'Terrace'), ('private_dining', 'Private Dining'), ('bar_area', 'Bar Area'), ('garden', 'Garden')], default='main_dining', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('out_of_order', 'Out of Order')], default='available', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangular', 'Rectangular'), ('booth', 'Booth')], default='round', max_length=15)),
                ('position_x', models.IntegerField(default=0, help_text='X coordinate for floor plan')),
                ('position_y', models.IntegerField(default=0, help_text='Y coordinate for floor plan')),
                ('last_occupied_at', models.DateTimeField(blank=True, null=True)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_view', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('notes', models.TextField(blank=True)),
                ('assigned_waiter', models.ForeignKey(blank=True, limit_choices_to={'role': 'waiter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to=settings.AUTH_USER_MODEL)),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='orders.order')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'tables',
                'ordering': ['section', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(max_length=20, unique=True)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=17)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('party_size', models.PositiveIntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=15)),
                ('special_requests', models.TextField(blank=True)),
                ('occasion', models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('business', 'Business Meeting'), ('date', 'Date Night'), ('family', 'Family Gathering'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table')),
            ],
            options={
                'verbose_name': 'Table Reservation',
                'verbose_name_plural': 'Table Reservations',
                'db_table': 'table_reservations',
                'ordering': ['reservation_date', 'reservation_time'],
                'unique_together': {('table', 'reservation_date', 'reservation_time')},
            },
        ),
    ]
