# Generated by Django 5.0.2 on 2025-09-30 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'menu_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Preparation time in minutes')),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('spice_level', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra_hot', 'Extra Hot')], default='mild', max_length=10)),
                ('requires_ingredients', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['category', 'display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost for this modifier', max_digits=8)),
                ('modifier_type', models.CharField(choices=[('extra', 'Extra'), ('substitute', 'Substitute'), ('remove', 'Remove'), ('sauce', 'Sauce'), ('size', 'Size')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('max_quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Modifier',
                'verbose_name_plural': 'Menu Item Modifiers',
                'db_table': 'menu_item_modifiers',
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('is_optional', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Ingredient',
                'verbose_name_plural': 'Menu Item Ingredients',
                'db_table': 'menu_item_ingredients',
                'unique_together': {('menu_item', 'ingredient_name')},
            },
        ),
    ]
