# Generated by Django 5.0.1 on 2025-10-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_image_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
