# Generated by Django 5.0.1 on 2025-10-02 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_image_url_remove_menuitem_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='is_gluten_free',
            new_name='is_special',
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='unit',
            field=models.CharField(help_text='e.g., grams, ml, units', max_length=20),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='requires_ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='spice_level',
        ),
    ]
